objc_library(
    name = "ios",
    visibility = [
        "//googlemac/iPhone/Nearby/HelloSetup:__subpackages__",
    ],
    deps = [
        "//googlemac/iPhone/Shared/Nearby/Connections:Platform",
    ],
)
