[package]
name = "presence_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["sync", "rt-multi-thread"] }
log = "0.4.20"
env_logger = "0.11.2"