# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Pod::Spec.new do |spec|
  spec.name = 'NearbyCoreAdapter'
  spec.version = '0.0.1'
  spec.summary = 'Objective-C adapter and C++ core for Nearby Connections.'
  spec.homepage = 'https://github.com/google/nearby'
  spec.license = { :type => 'Apache-2.0', :file => 'LICENSE' }
  spec.author = 'Google LLC'
  spec.source = { :git => 'https://github.com/google/nearby.git', :tag => "cocoapods-#{spec.version}", :submodules => true }
  spec.ios.deployment_target = '13.0'
  spec.dependency 'NearbyAbseil', '20260107.1'
  spec.dependency 'NearbyBoringSSL', '0.7.2'
  spec.source_files = [
    "compiled_proto/**/*.{h,c,cc,cpp,m,mm}",
    "connections/**/*.{h,c,cc,cpp,m,mm}",
    "internal/**/*.{h,c,cc,cpp,m,mm}",
    "proto/**/*.{h,c,cc,cpp,m,mm}",
    "connections/swift/NearbyCoreAdapter/Sources/**/*.{h,c,cc,cpp,m,mm}",
    "third_party/ukey2/ukey2/src/securemessage/src/securemessage/**/*.{h,c,cc,cpp,m,mm}",
    "third_party/ukey2/ukey2/src/main/cpp/src/securegcm/**/*.{h,c,cc,cpp,m,mm}",
    "third_party/ukey2/compiled_proto/**/*.{h,c,cc,cpp,m,mm}",
    "third_party/protobuf/src/google/protobuf/**/*.{h,c,cc,cpp,m,mm}",
    "third_party/protobuf/third_party/utf8_range/utf8_validity.h",
    "third_party/protobuf/third_party/utf8_range/utf8_range.h",
    "third_party/protobuf/third_party/utf8_range/utf8_range.c",
    "third_party/smhasher/smhasher/src/MurmurHash3.cpp",
    "third_party/json/EmptySwiftPackageManagerFile.cpp",
  ]
  spec.exclude_files = [
    'compiled_proto/connections/cpp/**/*',
    'connections/c/**/*',
    'connections/dart/**/*',
    'internal/platform/implementation/g3/**/*',
    'internal/platform/implementation/apple/Flags/Tests/**/*',
    'internal/platform/implementation/apple/Log/Tests/**/*',
    'internal/platform/implementation/apple/Mediums/BLE/Tests/**/*',
    'internal/platform/implementation/apple/Mediums/BLE/Sockets/Tests/**/*',
    'internal/platform/implementation/apple/Mediums/CoreLocation/CLLocationManager/Fake/**/*',
    'internal/platform/implementation/apple/Mediums/Hotspot/Tests/**/*',
    'internal/platform/implementation/apple/Mediums/WiFiCommon/Tests/**/*',
    'internal/platform/implementation/apple/Tests/**/*',
    'internal/platform/implementation/windows/**/*',
    'connections/implementation/fuzzers/**/*',
    'connections/listeners_test.cc',
    'connections/strategy_test.cc',
    'connections/implementation/offline_frames_test.cc',
    'connections/implementation/offline_service_controller_test.cc',
    'connections/implementation/encryption_runner_test.cc',
    'connections/implementation/p2p_cluster_pcp_handler_test.cc',
    'connections/implementation/p2p_point_to_point_pcp_handler_test.cc',
    'connections/implementation/p2p_star_pcp_handler_test.cc',
    'connections/implementation/base_pcp_handler_test.cc',
    'connections/implementation/injected_bluetooth_device_store_test.cc',
    'connections/implementation/internal_payload_factory_test.cc',
    'connections/implementation/client_proxy_test.cc',
    'connections/implementation/payload_manager_test.cc',
    'connections/implementation/offline_frames_validator_test.cc',
    'connections/implementation/service_controller_router_test.cc',
    'connections/implementation/analytics/analytics_recorder_impl_test.cc',
    'connections/implementation/mediums/advertisements/data_element_test.cc',
    'connections/implementation/mediums/advertisements/dct_advertisement_test.cc',
    'connections/implementation/mediums/advertisements/advertisement_util_test.cc',
    'connections/implementation/mediums/awdl_test.cc',
    'connections/implementation/mediums/awdl_bwu_handler_test.cc',
    'connections/implementation/mediums/ble_test.cc',
    'connections/implementation/mediums/ble/bloom_filter_test.cc',
    'connections/implementation/mediums/ble/ble_l2cap_packet_test.cc',
    'connections/implementation/mediums/ble/ble_packet_test.cc',
    'connections/implementation/mediums/ble/ble_advertisement_test.cc',
    'connections/implementation/mediums/ble/advertisement_read_result_test.cc',
    'connections/implementation/mediums/ble/ble_advertisement_header_test.cc',
    'connections/implementation/mediums/ble/ble_socket_test.cc',
    'connections/implementation/mediums/ble/ble_utils_test.cc',
    'connections/implementation/mediums/ble/discovered_peripheral_tracker_test.cc',
    'connections/implementation/mediums/ble/instant_on_lost_advertisement_test.cc',
    'connections/implementation/mediums/ble/instant_on_lost_manager_test.cc',
    'connections/implementation/mediums/bluetooth_bwu_handler_test.cc',
    'connections/implementation/mediums/bluetooth_classic_test.cc',
    'connections/implementation/mediums/bluetooth_radio_test.cc',
    'connections/implementation/mediums/lost_entity_tracker_test.cc',
    'connections/implementation/mediums/webrtc_peer_id_test.cc',
    'connections/implementation/mediums/webrtc_test.cc',
    'connections/implementation/mediums/wifi_direct_bwu_handler_test.cc',
    'connections/implementation/mediums/wifi_direct_test.cc',
    'connections/implementation/mediums/wifi_hotspot_bwu_handler_test.cc',
    'connections/implementation/mediums/wifi_hotspot_test.cc',
    'connections/implementation/mediums/wifi_lan_bwu_handler_test.cc',
    'connections/implementation/mediums/wifi_lan_test.cc',
    'connections/implementation/mediums/wifi_test.cc',
    'connections/implementation/endpoint_channel_manager_test.cc',
    'connections/implementation/bwu_manager_test.cc',
    'connections/implementation/base_bwu_handler_test.cc',
    'connections/implementation/endpoint_manager_test.cc',
    'connections/implementation/bluetooth_device_name_test.cc',
    'connections/implementation/wifi_lan_service_info_test.cc',
    'connections/implementation/pcp_manager_test.cc',
    'connections/implementation/ble_advertisement_test.cc',
    'connections/implementation/base_endpoint_channel_test.cc',
    'connections/v3/connections_device_test.cc',
    'connections/v3/connections_device_provider_test.cc',
    'connections/implementation/connections_authentication_transport_test.cc',
    'connections/core_test.cc',
    'connections/status_test.cc',
    'connections/payload_test.cc',
    'internal/base/bluetooth_address_test.cc',
    'internal/base/file_path_sanitize_test.cc',
    'internal/base/file_path_test.cc',
    'internal/base/files_test.cc',
    'internal/base/masker_test.cc',
    'internal/crypto/ed25519_unittest.cc',
    'internal/crypto_cros/aead_unittest.cc',
    'internal/crypto_cros/ec_private_key_unittest.cc',
    'internal/crypto_cros/ec_signature_creator_unittest.cc',
    'internal/crypto_cros/encryptor_unittest.cc',
    'internal/crypto_cros/hmac_unittest.cc',
    'internal/crypto_cros/rsa_private_key_unittest.cc',
    'internal/crypto_cros/secure_hash_unittest.cc',
    'internal/crypto_cros/sha2_unittest.cc',
    'internal/crypto_cros/signature_verifier_unittest.cc',
    'internal/crypto_cros/symmetric_key_unittest.cc',
    'internal/encoding/base85_test.cc',
    'internal/data/leveldb_data_set_test.cc',
    'internal/flags/nearby_flags_test.cc',
    'internal/platform/feature_flags_test.cc',
    'internal/platform/file_test.cc',
    'internal/platform/cancelable_alarm_test.cc',
    'internal/platform/crypto_test.cc',
    'internal/platform/byte_array_test.cc',
    'internal/platform/credential_storage_impl_test.cc',
    'internal/platform/implementation/device_info_test.cc',
    'internal/platform/implementation/g3/awdl_test.cc',
    'internal/platform/implementation/g3/ble_test.cc',
    'internal/platform/input_stream_test.cc',
    'internal/platform/mac_address_test.cc',
    'internal/platform/single_thread_executor_test.cc',
    'internal/platform/scheduled_executor_test.cc',
    'internal/platform/stream_reader_test.cc',
    'internal/platform/stream_writer_test.cc',
    'internal/platform/count_down_latch_test.cc',
    'internal/platform/pipe_test.cc',
    'internal/platform/timer_impl_test.cc',
    'internal/platform/task_runner_impl_test.cc',
    'internal/platform/uuid_test.cc',
    'internal/platform/wifi_lan_connection_info_test.cc',
    'internal/platform/wifi_direct_test.cc',
    'internal/platform/wifi_hotspot_test.cc',
    'internal/platform/wifi_lan_test.cc',
    'internal/platform/wifi_test.cc',
    'internal/platform/connection_info_test.cc',
    'internal/platform/condition_variable_test.cc',
    'internal/platform/bluetooth_classic_test.cc',
    'internal/platform/bluetooth_connection_info_test.cc',
    'internal/platform/mutex_test.cc',
    'internal/platform/atomic_reference_test.cc',
    'internal/platform/multi_thread_executor_test.cc',
    'internal/platform/ble_connection_info_test.cc',
    'internal/platform/ble_test.cc',
    'internal/platform/prng_test.cc',
    'internal/platform/implementation/apple/count_down_latch_test.cc',
    'internal/platform/implementation/apple/condition_variable_test.cc',
    'internal/platform/implementation/apple/mutex_test.cc',
    'internal/platform/implementation/apple/atomic_boolean_test.cc',
    'internal/platform/implementation/apple/atomic_uint32_test.cc',
    'internal/platform/implementation/apple/webrtc_platform.mm',
    'internal/platform/implementation/shared/file_test.cc',
    'internal/platform/implementation/wifi_utils_test.cc',
    'internal/platform/atomic_boolean_test.cc',
    'internal/platform/exception_test.cc',
    'internal/platform/expected_test.cc',
    'internal/platform/error_code_recorder_test.cc',
    'internal/platform/future_test.cc',
    'internal/platform/cancellation_flag_test.cc',
    'internal/platform/bluetooth_adapter_test.cc',
    'internal/platform/byte_utils_test.cc',
    'internal/platform/direct_executor_test.cc',
    'internal/platform/borrowable_test.cc',
    'internal/platform/implementation/windows/http_loader_test.cc',
    'internal/platform/blocking_queue_stream_test.cc',
    'internal/platform/service_address_test.cc',
    'internal/network/utils_test.cc',
    'internal/network/url_test.cc',
    'internal/network/http_response_test.cc',
    'internal/network/http_request_test.cc',
    'internal/network/http_client_impl_test.cc',
    'internal/network/http_status_code_test.cc',
    'internal/test/fake_clock_test.cc',
    'internal/test/fake_timer_test.cc',
    'internal/test/fake_device_info_test.cc',
    'internal/test/fake_task_runner_test.cc',
    'internal/test/fake_http_client_test.cc',
    'internal/weave/base_socket_test.cc',
    'internal/weave/control_packet_write_request_test.cc',
    'internal/weave/message_write_request_test.cc',
    'internal/weave/packet_test.cc',
    'internal/weave/packet_sequence_number_generator_test.cc',
    'internal/weave/packetizer_test.cc',
    'internal/weave/sockets/client_socket_test.cc',
    'internal/weave/sockets/server_socket_test.cc',
    'connections/implementation/offline_simulation_user.cc',
    'connections/implementation/simulation_user.cc',
    'connections/implementation/proto/**/*',
    'internal/proto/**/*',
    'proto/**/*',
    'internal/platform/implementation/apple/webrtc.h',
    'internal/platform/implementation/apple/webrtc.mm',
    'internal/platform/medium_environment.cc',
    'third_party/ukey2/ukey2/src/main/cpp/src/securegcm/ukey2_shell.cc',
    'third_party/protobuf/src/google/protobuf/bridge/**/*',
    'third_party/protobuf/src/google/protobuf/compiler/**/*',
    'third_party/protobuf/src/google/protobuf/testdata/**/*',
    'third_party/protobuf/src/google/protobuf/testing/**/*',
    'third_party/protobuf/src/google/protobuf/util/**/*',
    'third_party/protobuf/src/google/protobuf/no_field_presence_test.cc',
    'third_party/protobuf/src/google/protobuf/arenastring_unittest.cc',
    'third_party/protobuf/src/google/protobuf/reflection_ops_unittest.cc',
    'third_party/protobuf/src/google/protobuf/test_util_lite.cc',
    'third_party/protobuf/src/google/protobuf/any_test.cc',
    'third_party/protobuf/src/google/protobuf/io/tokenizer_unittest.cc',
    'third_party/protobuf/src/google/protobuf/test_util.cc',
    'third_party/protobuf/src/google/protobuf/map_test.cc',
    'third_party/protobuf/src/google/protobuf/drop_unknown_fields_test.cc',
    'third_party/protobuf/src/google/protobuf/descriptor_database_unittest.cc',
    'third_party/protobuf/src/google/protobuf/repeated_field_reflection_unittest.cc',
    'third_party/protobuf/src/google/protobuf/io/printer_unittest.cc',
    'third_party/protobuf/src/google/protobuf/io/zero_copy_stream_unittest.cc',
    'third_party/protobuf/src/google/protobuf/text_format_unittest.cc',
    'third_party/protobuf/src/google/protobuf/extension_set_unittest.cc',
    'third_party/protobuf/src/google/protobuf/preserve_unknown_enum_test.cc',
    'third_party/protobuf/src/google/protobuf/io/io_win32_unittest.cc',
    'third_party/protobuf/src/google/protobuf/lite_unittest.cc',
    'third_party/protobuf/src/google/protobuf/unknown_field_set_unittest.cc',
    'third_party/protobuf/src/google/protobuf/wire_format_unittest.cc',
    'third_party/protobuf/src/google/protobuf/generated_message_reflection_unittest.cc',
    'third_party/protobuf/src/google/protobuf/map_field_test.cc',
    'third_party/protobuf/src/google/protobuf/proto3_arena_lite_unittest.cc',
    'third_party/protobuf/src/google/protobuf/lite_arena_unittest.cc',
    'third_party/protobuf/src/google/protobuf/repeated_field_unittest.cc',
    'third_party/protobuf/src/google/protobuf/proto3_arena_unittest.cc',
    'third_party/protobuf/src/google/protobuf/inlined_string_field_unittest.cc',
    'third_party/protobuf/src/google/protobuf/io/coded_stream_unittest.cc',
    'third_party/protobuf/src/google/protobuf/proto3_lite_unittest.cc',
    'third_party/protobuf/src/google/protobuf/descriptor_unittest.cc',
    'third_party/protobuf/src/google/protobuf/stubs/common_unittest.cc',
    'third_party/protobuf/src/google/protobuf/arena_unittest.cc',
    'third_party/protobuf/src/google/protobuf/dynamic_message_unittest.cc',
    'third_party/protobuf/src/google/protobuf/message_unittest.cc',
    'third_party/protobuf/src/google/protobuf/well_known_types_unittest.cc',
    'third_party/protobuf/src/google/protobuf/reflection_tester.cc',
    'third_party/protobuf/src/google/protobuf/varint_shuffle_test.cc',
    'third_party/protobuf/src/google/protobuf/unredacted_debug_format_for_test_test.cc',
    'third_party/protobuf/src/google/protobuf/wire_format_unittest.h',
    'third_party/protobuf/src/google/protobuf/string_view_test.cc',
    'third_party/protobuf/src/google/protobuf/string_block_test.cc',
    'third_party/protobuf/src/google/protobuf/arena_align_test.cc',
    'third_party/protobuf/src/google/protobuf/arenaz_sampler_test.cc',
    'third_party/protobuf/src/google/protobuf/debug_counter_test.cc',
    'third_party/protobuf/src/google/protobuf/descriptor_visitor_test.cc',
    'third_party/protobuf/src/google/protobuf/edition_message_unittest.cc',
    'third_party/protobuf/src/google/protobuf/feature_resolver_test.cc',
    'third_party/protobuf/src/google/protobuf/generated_enum_util_test.cc',
    'third_party/protobuf/src/google/protobuf/generated_message_tctable_lite_test.cc',
    'third_party/protobuf/src/google/protobuf/has_bits_test.cc',
    'third_party/protobuf/src/google/protobuf/internal_feature_helper_test.cc',
    'third_party/protobuf/src/google/protobuf/internal_message_util_unittest.cc',
    'third_party/protobuf/src/google/protobuf/map_probe_benchmark.cc',
    'third_party/protobuf/src/google/protobuf/map_test_util.h',
    'third_party/protobuf/src/google/protobuf/micro_string_test.cc',
    'third_party/protobuf/src/google/protobuf/no_field_presence_map_test.cc',
    'third_party/protobuf/src/google/protobuf/port_test.cc',
    'third_party/protobuf/src/google/protobuf/raw_ptr_test.cc',
    'third_party/protobuf/src/google/protobuf/redaction_metric_test.cc',
    'third_party/protobuf/src/google/protobuf/reflection_mode_test.cc',
    'third_party/protobuf/src/google/protobuf/reflection_tester.h',
    'third_party/protobuf/src/google/protobuf/reflection_visit_fields_test.cc',
    'third_party/protobuf/src/google/protobuf/repeated_ptr_field_unittest.cc',
    'third_party/protobuf/src/google/protobuf/retention_test.cc',
    'third_party/protobuf/src/google/protobuf/string_piece_field_support_unittest.cc',
    'third_party/protobuf/src/google/protobuf/test_textproto.h',
    'third_party/protobuf/src/google/protobuf/test_util.h',
    'third_party/protobuf/src/google/protobuf/test_util2.h',
    'third_party/protobuf/src/google/protobuf/test_util_lite.h',
    'third_party/protobuf/src/google/protobuf/lazily_build_dependencies_test.cc',
    'third_party/protobuf/src/google/protobuf/json/json_test.cc',
    'third_party/protobuf/src/google/protobuf/json/internal/lexer_test.cc',
    'third_party/protobuf/src/google/protobuf/json/internal/zero_copy_buffered_stream_test.cc',
    'third_party/protobuf/src/google/protobuf/io/printer_death_test.cc',
    'third_party/protobuf/src/google/protobuf/io/test_zero_copy_stream.h',
    'third_party/protobuf/src/google/protobuf/io/test_zero_copy_stream_test.cc',
    'third_party/protobuf/src/google/protobuf/io/zero_copy_sink_test.cc',
    'connections/swift/**/Tests/**/*',
    'connections/swift/**/Example/**/*',
  ]
  spec.public_header_files = 'connections/swift/NearbyCoreAdapter/Sources/Public/NearbyCoreAdapter/*.h'
  spec.project_header_files = [
    'compiled_proto/**/*.h',
    'connections/*.h',
    'connections/implementation/**/*.h',
    'connections/v3/**/*.h',
    'internal/**/*.h',
    'proto/**/*.h',
    'third_party/**/*.h',
    'connections/swift/NearbyCoreAdapter/Sources/*.h',
  ]
  spec.preserve_paths = [
    'compiled_proto/**/*', 'connections/**/*', 'internal/**/*',
    'proto/**/*', 'third_party/**/*',
  ]
  spec.frameworks = 'Foundation', 'CoreBluetooth', 'CoreLocation', 'Network',
                    'NetworkExtension', 'Security', 'SystemConfiguration', 'UIKit'
  spec.libraries = 'c++', 'z'
  spec.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++20',
    'GCC_C_LANGUAGE_STANDARD' => 'c99',
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GITHUB_BUILD=1 NO_WEBRTC=1',
    'HEADER_SEARCH_PATHS' => [
      '$(inherited)',
      '"$(PODS_ROOT)/NearbyBoringSSL/src/include"',
      '"$(PODS_ROOT)/NearbyAbseil"',
      '"$(PODS_TARGET_SRCROOT)"',
      '"$(PODS_TARGET_SRCROOT)/compiled_proto"',
      '"$(PODS_TARGET_SRCROOT)/third_party/protobuf/src"',
      '"$(PODS_TARGET_SRCROOT)/third_party/protobuf/third_party/utf8_range"',
      '"$(PODS_TARGET_SRCROOT)/third_party/ukey2/ukey2"',
      '"$(PODS_TARGET_SRCROOT)/third_party/ukey2/include"',
      '"$(PODS_TARGET_SRCROOT)/third_party/ukey2/compiled_proto"',
      '"$(PODS_TARGET_SRCROOT)/third_party/ukey2/compiled_proto/src/main/proto"',
      '"$(PODS_TARGET_SRCROOT)/third_party/json/json/include"',
      '"$(PODS_TARGET_SRCROOT)/third_party/smhasher/include"',
      '"$(PODS_TARGET_SRCROOT)/third_party/smhasher/smhasher/src"',
    ].join(' '),
  }
end
