licenses(["notice"])

cc_library(
    name = "platform",
    textual_hdrs = glob(["**/*.h"]),
    visibility = [
        "//fastpair:__subpackages__",
    ],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)
