licenses(["notice"])

cc_library(
	name = "types",
    hdrs = [
        "device_info.h",
    ],
	srcs = [
	    "device_info.cc",
	],
    deps = [
        "//internal/platform/implementation:types",
        "//internal/platform:logging",
        "@com_google_absl//absl/strings",
        "@libsystemd//:lib",
    ],
)

