load("//security/fuzzing/blaze:cc_fuzz_target.bzl", "cc_fuzz_target")

cc_fuzz_target(
    name = "offline_frames_fuzzer",
    srcs = ["offline_frames_fuzzer.cc"],
    componentid = 148515,
    deps = [
        "//core/internal",
        "//platform/base",
        "//security/fuzzing/blaze:default_init_google_for_cc_fuzz_target",
    ],
)
