cc_library(
    name = "config",
    hdrs = [
        "config.h",
    ],
    visibility = [
        "//visibility:private",
    ],
)

cc_library(
    name = "string",
    hdrs = [
        "string.h",
    ],
    visibility = [
    ],
    deps = [
        ":config",
    ],
)
