// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/proto/credential.proto

#include "internal/proto/credential.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace nearby {
namespace internal {
constexpr LocalCredential_ConsumedSaltsEntry_DoNotUse::LocalCredential_ConsumedSaltsEntry_DoNotUse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct LocalCredential_ConsumedSaltsEntry_DoNotUseDefaultTypeInternal {
  constexpr LocalCredential_ConsumedSaltsEntry_DoNotUseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~LocalCredential_ConsumedSaltsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    LocalCredential_ConsumedSaltsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT LocalCredential_ConsumedSaltsEntry_DoNotUseDefaultTypeInternal _LocalCredential_ConsumedSaltsEntry_DoNotUse_default_instance_;
constexpr LocalCredential::LocalCredential(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : consumed_salts_(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{})
  , secret_id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , authenticity_key_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , verification_key_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , metadata_encryption_key_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , device_metadata_(nullptr)
  , start_time_millis_(uint64_t{0u})
  , end_time_millis_(uint64_t{0u})
  , identity_type_(0)
{}
struct LocalCredentialDefaultTypeInternal {
  constexpr LocalCredentialDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~LocalCredentialDefaultTypeInternal() {}
  union {
    LocalCredential _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT LocalCredentialDefaultTypeInternal _LocalCredential_default_instance_;
constexpr SharedCredential::SharedCredential(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : secret_id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , authenticity_key_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , verification_key_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , encrypted_metadata_bytes_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , metadata_encryption_key_tag_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , start_time_millis_(uint64_t{0u})
  , end_time_millis_(uint64_t{0u})
  , identity_type_(0)
{}
struct SharedCredentialDefaultTypeInternal {
  constexpr SharedCredentialDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SharedCredentialDefaultTypeInternal() {}
  union {
    SharedCredential _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SharedCredentialDefaultTypeInternal _SharedCredential_default_instance_;
}  // namespace internal
}  // namespace nearby
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_internal_2fproto_2fcredential_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_internal_2fproto_2fcredential_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_internal_2fproto_2fcredential_2eproto = nullptr;

const uint32_t TableStruct_internal_2fproto_2fcredential_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, identity_type_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, secret_id_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, authenticity_key_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, verification_key_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, start_time_millis_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, end_time_millis_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, consumed_salts_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, metadata_encryption_key_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::LocalCredential, device_metadata_),
  7,
  0,
  1,
  2,
  5,
  6,
  ~0u,
  3,
  4,
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, identity_type_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, secret_id_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, authenticity_key_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, verification_key_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, start_time_millis_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, end_time_millis_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, encrypted_metadata_bytes_),
  PROTOBUF_FIELD_OFFSET(::nearby::internal::SharedCredential, metadata_encryption_key_tag_),
  7,
  0,
  1,
  2,
  5,
  6,
  3,
  4,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse)},
  { 10, 25, -1, sizeof(::nearby::internal::LocalCredential)},
  { 34, 48, -1, sizeof(::nearby::internal::SharedCredential)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nearby::internal::_LocalCredential_ConsumedSaltsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nearby::internal::_LocalCredential_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::nearby::internal::_SharedCredential_default_instance_),
};

const char descriptor_table_protodef_internal_2fproto_2fcredential_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037internal/proto/credential.proto\022\017nearb"
  "y.internal\032$internal/proto/device_metada"
  "ta.proto\"\354\004\n\017LocalCredential\0229\n\ridentity"
  "_type\030\001 \001(\0162\035.nearby.internal.IdentityTy"
  "peH\000\210\001\001\022\026\n\tsecret_id\030\002 \001(\014H\001\210\001\001\022\035\n\020authe"
  "nticity_key\030\003 \001(\014H\002\210\001\001\022\035\n\020verification_k"
  "ey\030\004 \001(\014H\003\210\001\001\022\036\n\021start_time_millis\030\005 \001(\004"
  "H\004\210\001\001\022\034\n\017end_time_millis\030\006 \001(\004H\005\210\001\001\022K\n\016c"
  "onsumed_salts\030\007 \003(\01323.nearby.internal.Lo"
  "calCredential.ConsumedSaltsEntry\022$\n\027meta"
  "data_encryption_key\030\010 \001(\014H\006\210\001\001\022=\n\017device"
  "_metadata\030\t \001(\0132\037.nearby.internal.Device"
  "MetadataH\007\210\001\001\0324\n\022ConsumedSaltsEntry\022\013\n\003k"
  "ey\030\001 \001(\r\022\r\n\005value\030\002 \001(\010:\0028\001B\020\n\016_identity"
  "_typeB\014\n\n_secret_idB\023\n\021_authenticity_key"
  "B\023\n\021_verification_keyB\024\n\022_start_time_mil"
  "lisB\022\n\020_end_time_millisB\032\n\030_metadata_enc"
  "ryption_keyB\022\n\020_device_metadata\"\343\003\n\020Shar"
  "edCredential\0229\n\ridentity_type\030\001 \001(\0162\035.ne"
  "arby.internal.IdentityTypeH\000\210\001\001\022\026\n\tsecre"
  "t_id\030\002 \001(\014H\001\210\001\001\022\035\n\020authenticity_key\030\003 \001("
  "\014H\002\210\001\001\022\035\n\020verification_key\030\004 \001(\014H\003\210\001\001\022\036\n"
  "\021start_time_millis\030\005 \001(\004H\004\210\001\001\022\034\n\017end_tim"
  "e_millis\030\006 \001(\004H\005\210\001\001\022%\n\030encrypted_metadat"
  "a_bytes\030\007 \001(\014H\006\210\001\001\022(\n\033metadata_encryptio"
  "n_key_tag\030\010 \001(\014H\007\210\001\001B\020\n\016_identity_typeB\014"
  "\n\n_secret_idB\023\n\021_authenticity_keyB\023\n\021_ve"
  "rification_keyB\024\n\022_start_time_millisB\022\n\020"
  "_end_time_millisB\033\n\031_encrypted_metadata_"
  "bytesB\036\n\034_metadata_encryption_key_tag*\234\001"
  "\n\014IdentityType\022\035\n\031IDENTITY_TYPE_UNSPECIF"
  "IED\020\000\022\031\n\025IDENTITY_TYPE_PRIVATE\020\001\022\031\n\025IDEN"
  "TITY_TYPE_TRUSTED\020\002\022\030\n\024IDENTITY_TYPE_PUB"
  "LIC\020\003\022\035\n\031IDENTITY_TYPE_PROVISIONED\020\004B\034\n\032"
  "com.google.nearby.presenceb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_internal_2fproto_2fcredential_2eproto_deps[1] = {
  &::descriptor_table_internal_2fproto_2fdevice_5fmetadata_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_internal_2fproto_2fcredential_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_internal_2fproto_2fcredential_2eproto = {
  false, false, 1394, descriptor_table_protodef_internal_2fproto_2fcredential_2eproto, "internal/proto/credential.proto", 
  &descriptor_table_internal_2fproto_2fcredential_2eproto_once, descriptor_table_internal_2fproto_2fcredential_2eproto_deps, 1, 3,
  schemas, file_default_instances, TableStruct_internal_2fproto_2fcredential_2eproto::offsets,
  file_level_metadata_internal_2fproto_2fcredential_2eproto, file_level_enum_descriptors_internal_2fproto_2fcredential_2eproto, file_level_service_descriptors_internal_2fproto_2fcredential_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_internal_2fproto_2fcredential_2eproto_getter() {
  return &descriptor_table_internal_2fproto_2fcredential_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_internal_2fproto_2fcredential_2eproto(&descriptor_table_internal_2fproto_2fcredential_2eproto);
namespace nearby {
namespace internal {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* IdentityType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_internal_2fproto_2fcredential_2eproto);
  return file_level_enum_descriptors_internal_2fproto_2fcredential_2eproto[0];
}
bool IdentityType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

LocalCredential_ConsumedSaltsEntry_DoNotUse::LocalCredential_ConsumedSaltsEntry_DoNotUse() {}
LocalCredential_ConsumedSaltsEntry_DoNotUse::LocalCredential_ConsumedSaltsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void LocalCredential_ConsumedSaltsEntry_DoNotUse::MergeFrom(const LocalCredential_ConsumedSaltsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata LocalCredential_ConsumedSaltsEntry_DoNotUse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_internal_2fproto_2fcredential_2eproto_getter, &descriptor_table_internal_2fproto_2fcredential_2eproto_once,
      file_level_metadata_internal_2fproto_2fcredential_2eproto[0]);
}

// ===================================================================

class LocalCredential::_Internal {
 public:
  using HasBits = decltype(std::declval<LocalCredential>()._has_bits_);
  static void set_has_identity_type(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_secret_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_authenticity_key(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_verification_key(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_start_time_millis(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_end_time_millis(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_metadata_encryption_key(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::nearby::internal::DeviceMetadata& device_metadata(const LocalCredential* msg);
  static void set_has_device_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

const ::nearby::internal::DeviceMetadata&
LocalCredential::_Internal::device_metadata(const LocalCredential* msg) {
  return *msg->device_metadata_;
}
void LocalCredential::clear_device_metadata() {
  if (device_metadata_ != nullptr) device_metadata_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
LocalCredential::LocalCredential(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  consumed_salts_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:nearby.internal.LocalCredential)
}
LocalCredential::LocalCredential(const LocalCredential& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  consumed_salts_.MergeFrom(from.consumed_salts_);
  secret_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    secret_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_secret_id()) {
    secret_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_secret_id(), 
      GetArenaForAllocation());
  }
  authenticity_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    authenticity_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_authenticity_key()) {
    authenticity_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_authenticity_key(), 
      GetArenaForAllocation());
  }
  verification_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    verification_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_verification_key()) {
    verification_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_verification_key(), 
      GetArenaForAllocation());
  }
  metadata_encryption_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    metadata_encryption_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_metadata_encryption_key()) {
    metadata_encryption_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_metadata_encryption_key(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_device_metadata()) {
    device_metadata_ = new ::nearby::internal::DeviceMetadata(*from.device_metadata_);
  } else {
    device_metadata_ = nullptr;
  }
  ::memcpy(&start_time_millis_, &from.start_time_millis_,
    static_cast<size_t>(reinterpret_cast<char*>(&identity_type_) -
    reinterpret_cast<char*>(&start_time_millis_)) + sizeof(identity_type_));
  // @@protoc_insertion_point(copy_constructor:nearby.internal.LocalCredential)
}

inline void LocalCredential::SharedCtor() {
secret_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  secret_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
authenticity_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  authenticity_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
verification_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  verification_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
metadata_encryption_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  metadata_encryption_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&device_metadata_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&identity_type_) -
    reinterpret_cast<char*>(&device_metadata_)) + sizeof(identity_type_));
}

LocalCredential::~LocalCredential() {
  // @@protoc_insertion_point(destructor:nearby.internal.LocalCredential)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void LocalCredential::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  secret_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  authenticity_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  verification_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  metadata_encryption_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete device_metadata_;
}

void LocalCredential::ArenaDtor(void* object) {
  LocalCredential* _this = reinterpret_cast< LocalCredential* >(object);
  (void)_this;
  _this->consumed_salts_. ~MapField();
}
inline void LocalCredential::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena) {
  if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &LocalCredential::ArenaDtor);
  }
}
void LocalCredential::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void LocalCredential::Clear() {
// @@protoc_insertion_point(message_clear_start:nearby.internal.LocalCredential)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  consumed_salts_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      secret_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      authenticity_key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      verification_key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      metadata_encryption_key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(device_metadata_ != nullptr);
      device_metadata_->Clear();
    }
  }
  if (cached_has_bits & 0x000000e0u) {
    ::memset(&start_time_millis_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&identity_type_) -
        reinterpret_cast<char*>(&start_time_millis_)) + sizeof(identity_type_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LocalCredential::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .nearby.internal.IdentityType identity_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_identity_type(static_cast<::nearby::internal::IdentityType>(val));
        } else
          goto handle_unusual;
        continue;
      // optional bytes secret_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_secret_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes authenticity_key = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_authenticity_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes verification_key = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_verification_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 start_time_millis = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_start_time_millis(&has_bits);
          start_time_millis_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 end_time_millis = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_end_time_millis(&has_bits);
          end_time_millis_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<uint32, bool> consumed_salts = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&consumed_salts_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional bytes metadata_encryption_key = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_metadata_encryption_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .nearby.internal.DeviceMetadata device_metadata = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_device_metadata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LocalCredential::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nearby.internal.LocalCredential)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .nearby.internal.IdentityType identity_type = 1;
  if (_internal_has_identity_type()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_identity_type(), target);
  }

  // optional bytes secret_id = 2;
  if (_internal_has_secret_id()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_secret_id(), target);
  }

  // optional bytes authenticity_key = 3;
  if (_internal_has_authenticity_key()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_authenticity_key(), target);
  }

  // optional bytes verification_key = 4;
  if (_internal_has_verification_key()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_verification_key(), target);
  }

  // optional uint64 start_time_millis = 5;
  if (_internal_has_start_time_millis()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_start_time_millis(), target);
  }

  // optional uint64 end_time_millis = 6;
  if (_internal_has_end_time_millis()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(6, this->_internal_end_time_millis(), target);
  }

  // map<uint32, bool> consumed_salts = 7;
  if (!this->_internal_consumed_salts().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, bool >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< uint32_t, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;

    if (stream->IsSerializationDeterministic() &&
        this->_internal_consumed_salts().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_consumed_salts().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< uint32_t, bool >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< uint32_t, bool >::const_iterator
          it = this->_internal_consumed_salts().begin();
          it != this->_internal_consumed_salts().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = LocalCredential_ConsumedSaltsEntry_DoNotUse::Funcs::InternalSerialize(7, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< uint32_t, bool >::const_iterator
          it = this->_internal_consumed_salts().begin();
          it != this->_internal_consumed_salts().end(); ++it) {
        target = LocalCredential_ConsumedSaltsEntry_DoNotUse::Funcs::InternalSerialize(7, it->first, it->second, target, stream);
      }
    }
  }

  // optional bytes metadata_encryption_key = 8;
  if (_internal_has_metadata_encryption_key()) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_metadata_encryption_key(), target);
  }

  // optional .nearby.internal.DeviceMetadata device_metadata = 9;
  if (_internal_has_device_metadata()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        9, _Internal::device_metadata(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nearby.internal.LocalCredential)
  return target;
}

size_t LocalCredential::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nearby.internal.LocalCredential)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint32, bool> consumed_salts = 7;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_consumed_salts_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< uint32_t, bool >::const_iterator
      it = this->_internal_consumed_salts().begin();
      it != this->_internal_consumed_salts().end(); ++it) {
    total_size += LocalCredential_ConsumedSaltsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes secret_id = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_secret_id());
    }

    // optional bytes authenticity_key = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_authenticity_key());
    }

    // optional bytes verification_key = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_verification_key());
    }

    // optional bytes metadata_encryption_key = 8;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_metadata_encryption_key());
    }

    // optional .nearby.internal.DeviceMetadata device_metadata = 9;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *device_metadata_);
    }

    // optional uint64 start_time_millis = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64SizePlusOne(this->_internal_start_time_millis());
    }

    // optional uint64 end_time_millis = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64SizePlusOne(this->_internal_end_time_millis());
    }

    // optional .nearby.internal.IdentityType identity_type = 1;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_identity_type());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LocalCredential::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    LocalCredential::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LocalCredential::GetClassData() const { return &_class_data_; }

void LocalCredential::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<LocalCredential *>(to)->MergeFrom(
      static_cast<const LocalCredential &>(from));
}


void LocalCredential::MergeFrom(const LocalCredential& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nearby.internal.LocalCredential)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  consumed_salts_.MergeFrom(from.consumed_salts_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_secret_id(from._internal_secret_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_authenticity_key(from._internal_authenticity_key());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_verification_key(from._internal_verification_key());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_set_metadata_encryption_key(from._internal_metadata_encryption_key());
    }
    if (cached_has_bits & 0x00000010u) {
      _internal_mutable_device_metadata()->::nearby::internal::DeviceMetadata::MergeFrom(from._internal_device_metadata());
    }
    if (cached_has_bits & 0x00000020u) {
      start_time_millis_ = from.start_time_millis_;
    }
    if (cached_has_bits & 0x00000040u) {
      end_time_millis_ = from.end_time_millis_;
    }
    if (cached_has_bits & 0x00000080u) {
      identity_type_ = from.identity_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LocalCredential::CopyFrom(const LocalCredential& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nearby.internal.LocalCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocalCredential::IsInitialized() const {
  return true;
}

void LocalCredential::InternalSwap(LocalCredential* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  consumed_salts_.InternalSwap(&other->consumed_salts_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &secret_id_, lhs_arena,
      &other->secret_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &authenticity_key_, lhs_arena,
      &other->authenticity_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &verification_key_, lhs_arena,
      &other->verification_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &metadata_encryption_key_, lhs_arena,
      &other->metadata_encryption_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LocalCredential, identity_type_)
      + sizeof(LocalCredential::identity_type_)
      - PROTOBUF_FIELD_OFFSET(LocalCredential, device_metadata_)>(
          reinterpret_cast<char*>(&device_metadata_),
          reinterpret_cast<char*>(&other->device_metadata_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LocalCredential::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_internal_2fproto_2fcredential_2eproto_getter, &descriptor_table_internal_2fproto_2fcredential_2eproto_once,
      file_level_metadata_internal_2fproto_2fcredential_2eproto[1]);
}

// ===================================================================

class SharedCredential::_Internal {
 public:
  using HasBits = decltype(std::declval<SharedCredential>()._has_bits_);
  static void set_has_identity_type(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_secret_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_authenticity_key(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_verification_key(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_start_time_millis(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_end_time_millis(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_encrypted_metadata_bytes(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_metadata_encryption_key_tag(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

SharedCredential::SharedCredential(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:nearby.internal.SharedCredential)
}
SharedCredential::SharedCredential(const SharedCredential& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  secret_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    secret_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_secret_id()) {
    secret_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_secret_id(), 
      GetArenaForAllocation());
  }
  authenticity_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    authenticity_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_authenticity_key()) {
    authenticity_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_authenticity_key(), 
      GetArenaForAllocation());
  }
  verification_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    verification_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_verification_key()) {
    verification_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_verification_key(), 
      GetArenaForAllocation());
  }
  encrypted_metadata_bytes_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    encrypted_metadata_bytes_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_encrypted_metadata_bytes()) {
    encrypted_metadata_bytes_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_encrypted_metadata_bytes(), 
      GetArenaForAllocation());
  }
  metadata_encryption_key_tag_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    metadata_encryption_key_tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_metadata_encryption_key_tag()) {
    metadata_encryption_key_tag_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_metadata_encryption_key_tag(), 
      GetArenaForAllocation());
  }
  ::memcpy(&start_time_millis_, &from.start_time_millis_,
    static_cast<size_t>(reinterpret_cast<char*>(&identity_type_) -
    reinterpret_cast<char*>(&start_time_millis_)) + sizeof(identity_type_));
  // @@protoc_insertion_point(copy_constructor:nearby.internal.SharedCredential)
}

inline void SharedCredential::SharedCtor() {
secret_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  secret_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
authenticity_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  authenticity_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
verification_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  verification_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
encrypted_metadata_bytes_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  encrypted_metadata_bytes_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
metadata_encryption_key_tag_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  metadata_encryption_key_tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&start_time_millis_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&identity_type_) -
    reinterpret_cast<char*>(&start_time_millis_)) + sizeof(identity_type_));
}

SharedCredential::~SharedCredential() {
  // @@protoc_insertion_point(destructor:nearby.internal.SharedCredential)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SharedCredential::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  secret_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  authenticity_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  verification_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  encrypted_metadata_bytes_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  metadata_encryption_key_tag_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SharedCredential::ArenaDtor(void* object) {
  SharedCredential* _this = reinterpret_cast< SharedCredential* >(object);
  (void)_this;
}
void SharedCredential::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SharedCredential::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SharedCredential::Clear() {
// @@protoc_insertion_point(message_clear_start:nearby.internal.SharedCredential)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      secret_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      authenticity_key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      verification_key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      encrypted_metadata_bytes_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      metadata_encryption_key_tag_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000e0u) {
    ::memset(&start_time_millis_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&identity_type_) -
        reinterpret_cast<char*>(&start_time_millis_)) + sizeof(identity_type_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SharedCredential::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .nearby.internal.IdentityType identity_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_identity_type(static_cast<::nearby::internal::IdentityType>(val));
        } else
          goto handle_unusual;
        continue;
      // optional bytes secret_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_secret_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes authenticity_key = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_authenticity_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes verification_key = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_verification_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 start_time_millis = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_start_time_millis(&has_bits);
          start_time_millis_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 end_time_millis = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_end_time_millis(&has_bits);
          end_time_millis_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes encrypted_metadata_bytes = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_encrypted_metadata_bytes();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes metadata_encryption_key_tag = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_metadata_encryption_key_tag();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SharedCredential::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:nearby.internal.SharedCredential)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .nearby.internal.IdentityType identity_type = 1;
  if (_internal_has_identity_type()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_identity_type(), target);
  }

  // optional bytes secret_id = 2;
  if (_internal_has_secret_id()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_secret_id(), target);
  }

  // optional bytes authenticity_key = 3;
  if (_internal_has_authenticity_key()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_authenticity_key(), target);
  }

  // optional bytes verification_key = 4;
  if (_internal_has_verification_key()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_verification_key(), target);
  }

  // optional uint64 start_time_millis = 5;
  if (_internal_has_start_time_millis()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_start_time_millis(), target);
  }

  // optional uint64 end_time_millis = 6;
  if (_internal_has_end_time_millis()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(6, this->_internal_end_time_millis(), target);
  }

  // optional bytes encrypted_metadata_bytes = 7;
  if (_internal_has_encrypted_metadata_bytes()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_encrypted_metadata_bytes(), target);
  }

  // optional bytes metadata_encryption_key_tag = 8;
  if (_internal_has_metadata_encryption_key_tag()) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_metadata_encryption_key_tag(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nearby.internal.SharedCredential)
  return target;
}

size_t SharedCredential::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nearby.internal.SharedCredential)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes secret_id = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_secret_id());
    }

    // optional bytes authenticity_key = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_authenticity_key());
    }

    // optional bytes verification_key = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_verification_key());
    }

    // optional bytes encrypted_metadata_bytes = 7;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_encrypted_metadata_bytes());
    }

    // optional bytes metadata_encryption_key_tag = 8;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_metadata_encryption_key_tag());
    }

    // optional uint64 start_time_millis = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64SizePlusOne(this->_internal_start_time_millis());
    }

    // optional uint64 end_time_millis = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64SizePlusOne(this->_internal_end_time_millis());
    }

    // optional .nearby.internal.IdentityType identity_type = 1;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_identity_type());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SharedCredential::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SharedCredential::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SharedCredential::GetClassData() const { return &_class_data_; }

void SharedCredential::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SharedCredential *>(to)->MergeFrom(
      static_cast<const SharedCredential &>(from));
}


void SharedCredential::MergeFrom(const SharedCredential& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nearby.internal.SharedCredential)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_secret_id(from._internal_secret_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_authenticity_key(from._internal_authenticity_key());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_verification_key(from._internal_verification_key());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_set_encrypted_metadata_bytes(from._internal_encrypted_metadata_bytes());
    }
    if (cached_has_bits & 0x00000010u) {
      _internal_set_metadata_encryption_key_tag(from._internal_metadata_encryption_key_tag());
    }
    if (cached_has_bits & 0x00000020u) {
      start_time_millis_ = from.start_time_millis_;
    }
    if (cached_has_bits & 0x00000040u) {
      end_time_millis_ = from.end_time_millis_;
    }
    if (cached_has_bits & 0x00000080u) {
      identity_type_ = from.identity_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SharedCredential::CopyFrom(const SharedCredential& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nearby.internal.SharedCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SharedCredential::IsInitialized() const {
  return true;
}

void SharedCredential::InternalSwap(SharedCredential* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &secret_id_, lhs_arena,
      &other->secret_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &authenticity_key_, lhs_arena,
      &other->authenticity_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &verification_key_, lhs_arena,
      &other->verification_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &encrypted_metadata_bytes_, lhs_arena,
      &other->encrypted_metadata_bytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &metadata_encryption_key_tag_, lhs_arena,
      &other->metadata_encryption_key_tag_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SharedCredential, identity_type_)
      + sizeof(SharedCredential::identity_type_)
      - PROTOBUF_FIELD_OFFSET(SharedCredential, start_time_millis_)>(
          reinterpret_cast<char*>(&start_time_millis_),
          reinterpret_cast<char*>(&other->start_time_millis_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SharedCredential::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_internal_2fproto_2fcredential_2eproto_getter, &descriptor_table_internal_2fproto_2fcredential_2eproto_once,
      file_level_metadata_internal_2fproto_2fcredential_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace internal
}  // namespace nearby
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse* Arena::CreateMaybeMessage< ::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nearby::internal::LocalCredential_ConsumedSaltsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::nearby::internal::LocalCredential* Arena::CreateMaybeMessage< ::nearby::internal::LocalCredential >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nearby::internal::LocalCredential >(arena);
}
template<> PROTOBUF_NOINLINE ::nearby::internal::SharedCredential* Arena::CreateMaybeMessage< ::nearby::internal::SharedCredential >(Arena* arena) {
  return Arena::CreateMessageInternal< ::nearby::internal::SharedCredential >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
