// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: internal/proto/metadata.proto
// Protobuf C++ Version: 6.33.3

#include "internal/proto/metadata.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nearby {
namespace internal {

inline constexpr PresenceIdentity::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        identity_provider_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        identity_type_{static_cast< ::nearby::internal::IdentityType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR PresenceIdentity::PresenceIdentity(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(PresenceIdentity_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PresenceIdentityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PresenceIdentityDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PresenceIdentityDefaultTypeInternal() {}
  union {
    PresenceIdentity _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PresenceIdentityDefaultTypeInternal _PresenceIdentity_default_instance_;

inline constexpr Metadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        account_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_profile_url_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bluetooth_mac_address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_type_{static_cast< ::nearby::internal::DeviceType >(0)},
        instance_type_{static_cast< ::nearby::internal::InstanceType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Metadata::Metadata(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(Metadata_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetadataDefaultTypeInternal() {}
  union {
    Metadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetadataDefaultTypeInternal _Metadata_default_instance_;

inline constexpr DeviceIdentityMetaData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        device_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bluetooth_mac_address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_model_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_manufacturer_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        identity_{nullptr},
        device_type_{static_cast< ::nearby::internal::DeviceType >(0)},
        instance_type_{static_cast< ::nearby::internal::InstanceType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR DeviceIdentityMetaData::DeviceIdentityMetaData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(DeviceIdentityMetaData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DeviceIdentityMetaDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeviceIdentityMetaDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeviceIdentityMetaDataDefaultTypeInternal() {}
  union {
    DeviceIdentityMetaData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeviceIdentityMetaDataDefaultTypeInternal _DeviceIdentityMetaData_default_instance_;
}  // namespace internal
}  // namespace nearby
namespace nearby {
namespace internal {
PROTOBUF_CONSTINIT const uint32_t DeviceType_internal_data_[] = {
    720896u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    DeviceType_strings[11] = {};

static const char DeviceType_names[] = {
    "DEVICE_TYPE_AUTOMOTIVE"
    "DEVICE_TYPE_CHROMEOS"
    "DEVICE_TYPE_DISPLAY"
    "DEVICE_TYPE_FOLDABLE"
    "DEVICE_TYPE_LAPTOP"
    "DEVICE_TYPE_PHONE"
    "DEVICE_TYPE_SPEAKER"
    "DEVICE_TYPE_TABLET"
    "DEVICE_TYPE_TV"
    "DEVICE_TYPE_UNKNOWN"
    "DEVICE_TYPE_WATCH"
};

static const ::google::protobuf::internal::EnumEntry DeviceType_entries[] = {
    {{&DeviceType_names[0], 22}, 9},
    {{&DeviceType_names[22], 20}, 7},
    {{&DeviceType_names[42], 19}, 3},
    {{&DeviceType_names[61], 20}, 8},
    {{&DeviceType_names[81], 18}, 4},
    {{&DeviceType_names[99], 17}, 1},
    {{&DeviceType_names[116], 19}, 10},
    {{&DeviceType_names[135], 18}, 2},
    {{&DeviceType_names[153], 14}, 5},
    {{&DeviceType_names[167], 19}, 0},
    {{&DeviceType_names[186], 17}, 6},
};

static const int DeviceType_entries_by_number[] = {
    9,  // 0 -> DEVICE_TYPE_UNKNOWN
    5,  // 1 -> DEVICE_TYPE_PHONE
    7,  // 2 -> DEVICE_TYPE_TABLET
    2,  // 3 -> DEVICE_TYPE_DISPLAY
    4,  // 4 -> DEVICE_TYPE_LAPTOP
    8,  // 5 -> DEVICE_TYPE_TV
    10,  // 6 -> DEVICE_TYPE_WATCH
    1,  // 7 -> DEVICE_TYPE_CHROMEOS
    3,  // 8 -> DEVICE_TYPE_FOLDABLE
    0,  // 9 -> DEVICE_TYPE_AUTOMOTIVE
    6,  // 10 -> DEVICE_TYPE_SPEAKER
};

const ::std::string& DeviceType_Name(DeviceType value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      DeviceType_entries, DeviceType_entries_by_number, 11,
      DeviceType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(DeviceType_entries,
                                  DeviceType_entries_by_number,
                                  11, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : DeviceType_strings[idx].get();
}

bool DeviceType_Parse(::absl::string_view name, DeviceType* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      DeviceType_entries, 11, name, &int_value);
  if (success) {
    *value = static_cast<DeviceType>(int_value);
  }
  return success;
}
PROTOBUF_CONSTINIT const uint32_t InstanceType_internal_data_[] = {
    196608u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    InstanceType_strings[3] = {};

static const char InstanceType_names[] = {
    "INSTANCE_TYPE_MAIN"
    "INSTANCE_TYPE_SECONDARY"
    "INSTANCE_TYPE_UNKNOWN"
};

static const ::google::protobuf::internal::EnumEntry InstanceType_entries[] = {
    {{&InstanceType_names[0], 18}, 1},
    {{&InstanceType_names[18], 23}, 2},
    {{&InstanceType_names[41], 21}, 0},
};

static const int InstanceType_entries_by_number[] = {
    2,  // 0 -> INSTANCE_TYPE_UNKNOWN
    0,  // 1 -> INSTANCE_TYPE_MAIN
    1,  // 2 -> INSTANCE_TYPE_SECONDARY
};

const ::std::string& InstanceType_Name(InstanceType value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      InstanceType_entries, InstanceType_entries_by_number, 3,
      InstanceType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(InstanceType_entries,
                                  InstanceType_entries_by_number,
                                  3, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : InstanceType_strings[idx].get();
}

bool InstanceType_Parse(::absl::string_view name, InstanceType* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      InstanceType_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<InstanceType>(int_value);
  }
  return success;
}
// ===================================================================

class DeviceIdentityMetaData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DeviceIdentityMetaData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_._has_bits_);
};

DeviceIdentityMetaData::DeviceIdentityMetaData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, DeviceIdentityMetaData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nearby.internal.DeviceIdentityMetaData)
}
PROTOBUF_NDEBUG_INLINE DeviceIdentityMetaData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nearby::internal::DeviceIdentityMetaData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        device_name_(arena, from.device_name_),
        bluetooth_mac_address_(arena, from.bluetooth_mac_address_),
        device_id_(arena, from.device_id_),
        device_model_name_(arena, from.device_model_name_),
        device_manufacturer_(arena, from.device_manufacturer_) {}

DeviceIdentityMetaData::DeviceIdentityMetaData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DeviceIdentityMetaData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, DeviceIdentityMetaData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DeviceIdentityMetaData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.identity_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.identity_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, device_type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, device_type_),
           offsetof(Impl_, instance_type_) -
               offsetof(Impl_, device_type_) +
               sizeof(Impl_::instance_type_));

  // @@protoc_insertion_point(copy_constructor:nearby.internal.DeviceIdentityMetaData)
}
PROTOBUF_NDEBUG_INLINE DeviceIdentityMetaData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        device_name_(arena),
        bluetooth_mac_address_(arena),
        device_id_(arena),
        device_model_name_(arena),
        device_manufacturer_(arena) {}

inline void DeviceIdentityMetaData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, identity_),
           0,
           offsetof(Impl_, instance_type_) -
               offsetof(Impl_, identity_) +
               sizeof(Impl_::instance_type_));
}
DeviceIdentityMetaData::~DeviceIdentityMetaData() {
  // @@protoc_insertion_point(destructor:nearby.internal.DeviceIdentityMetaData)
  SharedDtor(*this);
}
inline void DeviceIdentityMetaData::SharedDtor(MessageLite& self) {
  DeviceIdentityMetaData& this_ = static_cast<DeviceIdentityMetaData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.device_name_.Destroy();
  this_._impl_.bluetooth_mac_address_.Destroy();
  this_._impl_.device_id_.Destroy();
  this_._impl_.device_model_name_.Destroy();
  this_._impl_.device_manufacturer_.Destroy();
  delete this_._impl_.identity_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DeviceIdentityMetaData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DeviceIdentityMetaData(arena);
}
constexpr auto DeviceIdentityMetaData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DeviceIdentityMetaData),
                                            alignof(DeviceIdentityMetaData));
}
constexpr auto DeviceIdentityMetaData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<39>{
      {
          &_DeviceIdentityMetaData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DeviceIdentityMetaData::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<DeviceIdentityMetaData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DeviceIdentityMetaData::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<DeviceIdentityMetaData>(), &DeviceIdentityMetaData::ByteSizeLong,
              &DeviceIdentityMetaData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_._cached_size_),
          true,
      },
      "nearby.internal.DeviceIdentityMetaData",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<39> DeviceIdentityMetaData_class_data_ =
    DeviceIdentityMetaData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DeviceIdentityMetaData::GetClassData() const {
  return DeviceIdentityMetaData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 1, 102, 2>
DeviceIdentityMetaData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    DeviceIdentityMetaData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nearby::internal::DeviceIdentityMetaData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .nearby.internal.PresenceIdentity identity = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 5, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.identity_)}},
    // .nearby.internal.DeviceType device_type = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 6, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_type_)}},
    // string device_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_name_)}},
    // bytes bluetooth_mac_address = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.bluetooth_mac_address_)}},
    // .nearby.internal.InstanceType instance_type = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 7, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.instance_type_)}},
    // bytes device_id = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 2, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_id_)}},
    // string device_model_name = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 3, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_model_name_)}},
    // string device_manufacturer = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 4, 0,
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_manufacturer_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nearby.internal.DeviceType device_type = 1;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_type_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string device_name = 2;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes bluetooth_mac_address = 3;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.bluetooth_mac_address_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // .nearby.internal.InstanceType instance_type = 4;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.instance_type_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bytes device_id = 5;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // string device_model_name = 6;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_model_name_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string device_manufacturer = 7;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.device_manufacturer_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .nearby.internal.PresenceIdentity identity = 8;
    {PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.identity_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::nearby::internal::PresenceIdentity>()},
  }},
  {{
    "\46\0\13\0\0\0\21\23\0\0\0\0\0\0\0\0"
    "nearby.internal.DeviceIdentityMetaData"
    "device_name"
    "device_model_name"
    "device_manufacturer"
  }},
};
PROTOBUF_NOINLINE void DeviceIdentityMetaData::Clear() {
// @@protoc_insertion_point(message_clear_start:nearby.internal.DeviceIdentityMetaData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.device_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.bluetooth_mac_address_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.device_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.device_model_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.device_manufacturer_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.identity_ != nullptr);
      _impl_.identity_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000c0U)) {
    ::memset(&_impl_.device_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.instance_type_) -
        reinterpret_cast<char*>(&_impl_.device_type_)) + sizeof(_impl_.instance_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DeviceIdentityMetaData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DeviceIdentityMetaData& this_ = static_cast<const DeviceIdentityMetaData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DeviceIdentityMetaData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DeviceIdentityMetaData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nearby.internal.DeviceIdentityMetaData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .nearby.internal.DeviceType device_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_device_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_device_type(), target);
    }
  }

  // string device_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_device_name().empty()) {
      const ::std::string& _s = this_._internal_device_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.DeviceIdentityMetaData.device_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // bytes bluetooth_mac_address = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_bluetooth_mac_address().empty()) {
      const ::std::string& _s = this_._internal_bluetooth_mac_address();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // .nearby.internal.InstanceType instance_type = 4;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_instance_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_instance_type(), target);
    }
  }

  // bytes device_id = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_device_id().empty()) {
      const ::std::string& _s = this_._internal_device_id();
      target = stream->WriteBytesMaybeAliased(5, _s, target);
    }
  }

  // string device_model_name = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_device_model_name().empty()) {
      const ::std::string& _s = this_._internal_device_model_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.DeviceIdentityMetaData.device_model_name");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // string device_manufacturer = 7;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_device_manufacturer().empty()) {
      const ::std::string& _s = this_._internal_device_manufacturer();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.DeviceIdentityMetaData.device_manufacturer");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // .nearby.internal.PresenceIdentity identity = 8;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *this_._impl_.identity_, this_._impl_.identity_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nearby.internal.DeviceIdentityMetaData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DeviceIdentityMetaData::ByteSizeLong(const MessageLite& base) {
  const DeviceIdentityMetaData& this_ = static_cast<const DeviceIdentityMetaData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DeviceIdentityMetaData::ByteSizeLong() const {
  const DeviceIdentityMetaData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nearby.internal.DeviceIdentityMetaData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string device_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_device_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_device_name());
      }
    }
    // bytes bluetooth_mac_address = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_bluetooth_mac_address().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_bluetooth_mac_address());
      }
    }
    // bytes device_id = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_device_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_device_id());
      }
    }
    // string device_model_name = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_device_model_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_device_model_name());
      }
    }
    // string device_manufacturer = 7;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_device_manufacturer().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_device_manufacturer());
      }
    }
    // .nearby.internal.PresenceIdentity identity = 8;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.identity_);
    }
    // .nearby.internal.DeviceType device_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_device_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_device_type());
      }
    }
    // .nearby.internal.InstanceType instance_type = 4;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_instance_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_instance_type());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void DeviceIdentityMetaData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<DeviceIdentityMetaData*>(&to_msg);
  auto& from = static_cast<const DeviceIdentityMetaData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nearby.internal.DeviceIdentityMetaData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_device_name().empty()) {
        _this->_internal_set_device_name(from._internal_device_name());
      } else {
        if (_this->_impl_.device_name_.IsDefault()) {
          _this->_internal_set_device_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_bluetooth_mac_address().empty()) {
        _this->_internal_set_bluetooth_mac_address(from._internal_bluetooth_mac_address());
      } else {
        if (_this->_impl_.bluetooth_mac_address_.IsDefault()) {
          _this->_internal_set_bluetooth_mac_address("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_device_id().empty()) {
        _this->_internal_set_device_id(from._internal_device_id());
      } else {
        if (_this->_impl_.device_id_.IsDefault()) {
          _this->_internal_set_device_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_device_model_name().empty()) {
        _this->_internal_set_device_model_name(from._internal_device_model_name());
      } else {
        if (_this->_impl_.device_model_name_.IsDefault()) {
          _this->_internal_set_device_model_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_device_manufacturer().empty()) {
        _this->_internal_set_device_manufacturer(from._internal_device_manufacturer());
      } else {
        if (_this->_impl_.device_manufacturer_.IsDefault()) {
          _this->_internal_set_device_manufacturer("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.identity_ != nullptr);
      if (_this->_impl_.identity_ == nullptr) {
        _this->_impl_.identity_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.identity_);
      } else {
        _this->_impl_.identity_->MergeFrom(*from._impl_.identity_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_device_type() != 0) {
        _this->_impl_.device_type_ = from._impl_.device_type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_instance_type() != 0) {
        _this->_impl_.instance_type_ = from._impl_.instance_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void DeviceIdentityMetaData::CopyFrom(const DeviceIdentityMetaData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nearby.internal.DeviceIdentityMetaData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DeviceIdentityMetaData::InternalSwap(DeviceIdentityMetaData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_name_, &other->_impl_.device_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bluetooth_mac_address_, &other->_impl_.bluetooth_mac_address_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_id_, &other->_impl_.device_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_model_name_, &other->_impl_.device_model_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_manufacturer_, &other->_impl_.device_manufacturer_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.instance_type_)
      + sizeof(DeviceIdentityMetaData::_impl_.instance_type_)
      - PROTOBUF_FIELD_OFFSET(DeviceIdentityMetaData, _impl_.identity_)>(
          reinterpret_cast<char*>(&_impl_.identity_),
          reinterpret_cast<char*>(&other->_impl_.identity_));
}

// ===================================================================

class PresenceIdentity::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PresenceIdentity>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PresenceIdentity, _impl_._has_bits_);
};

PresenceIdentity::PresenceIdentity(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, PresenceIdentity_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nearby.internal.PresenceIdentity)
}
PROTOBUF_NDEBUG_INLINE PresenceIdentity::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nearby::internal::PresenceIdentity& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        identity_provider_name_(arena, from.identity_provider_name_) {}

PresenceIdentity::PresenceIdentity(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PresenceIdentity& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, PresenceIdentity_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PresenceIdentity* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.identity_type_ = from._impl_.identity_type_;

  // @@protoc_insertion_point(copy_constructor:nearby.internal.PresenceIdentity)
}
PROTOBUF_NDEBUG_INLINE PresenceIdentity::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        identity_provider_name_(arena) {}

inline void PresenceIdentity::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.identity_type_ = {};
}
PresenceIdentity::~PresenceIdentity() {
  // @@protoc_insertion_point(destructor:nearby.internal.PresenceIdentity)
  SharedDtor(*this);
}
inline void PresenceIdentity::SharedDtor(MessageLite& self) {
  PresenceIdentity& this_ = static_cast<PresenceIdentity&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.identity_provider_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PresenceIdentity::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PresenceIdentity(arena);
}
constexpr auto PresenceIdentity::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PresenceIdentity),
                                            alignof(PresenceIdentity));
}
constexpr auto PresenceIdentity::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<33>{
      {
          &_PresenceIdentity_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PresenceIdentity::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<PresenceIdentity>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PresenceIdentity::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<PresenceIdentity>(), &PresenceIdentity::ByteSizeLong,
              &PresenceIdentity::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PresenceIdentity, _impl_._cached_size_),
          true,
      },
      "nearby.internal.PresenceIdentity",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<33> PresenceIdentity_class_data_ =
    PresenceIdentity::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PresenceIdentity::GetClassData() const {
  return PresenceIdentity_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 63, 2>
PresenceIdentity::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PresenceIdentity, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PresenceIdentity_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nearby::internal::PresenceIdentity>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string identity_provider_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(PresenceIdentity, _impl_.identity_provider_name_)}},
    // .nearby.internal.IdentityType identity_type = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(PresenceIdentity, _impl_.identity_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nearby.internal.IdentityType identity_type = 1;
    {PROTOBUF_FIELD_OFFSET(PresenceIdentity, _impl_.identity_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string identity_provider_name = 2;
    {PROTOBUF_FIELD_OFFSET(PresenceIdentity, _impl_.identity_provider_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\0\26\0\0\0\0\0"
    "nearby.internal.PresenceIdentity"
    "identity_provider_name"
  }},
};
PROTOBUF_NOINLINE void PresenceIdentity::Clear() {
// @@protoc_insertion_point(message_clear_start:nearby.internal.PresenceIdentity)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.identity_provider_name_.ClearNonDefaultToEmpty();
  }
  _impl_.identity_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PresenceIdentity::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PresenceIdentity& this_ = static_cast<const PresenceIdentity&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PresenceIdentity::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PresenceIdentity& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nearby.internal.PresenceIdentity)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .nearby.internal.IdentityType identity_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_identity_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_identity_type(), target);
    }
  }

  // string identity_provider_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_identity_provider_name().empty()) {
      const ::std::string& _s = this_._internal_identity_provider_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.PresenceIdentity.identity_provider_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nearby.internal.PresenceIdentity)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PresenceIdentity::ByteSizeLong(const MessageLite& base) {
  const PresenceIdentity& this_ = static_cast<const PresenceIdentity&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PresenceIdentity::ByteSizeLong() const {
  const PresenceIdentity& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nearby.internal.PresenceIdentity)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string identity_provider_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_identity_provider_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_identity_provider_name());
      }
    }
    // .nearby.internal.IdentityType identity_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_identity_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_identity_type());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void PresenceIdentity::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PresenceIdentity*>(&to_msg);
  auto& from = static_cast<const PresenceIdentity&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nearby.internal.PresenceIdentity)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_identity_provider_name().empty()) {
        _this->_internal_set_identity_provider_name(from._internal_identity_provider_name());
      } else {
        if (_this->_impl_.identity_provider_name_.IsDefault()) {
          _this->_internal_set_identity_provider_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_identity_type() != 0) {
        _this->_impl_.identity_type_ = from._impl_.identity_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void PresenceIdentity::CopyFrom(const PresenceIdentity& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nearby.internal.PresenceIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PresenceIdentity::InternalSwap(PresenceIdentity* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.identity_provider_name_, &other->_impl_.identity_provider_name_, arena);
  swap(_impl_.identity_type_, other->_impl_.identity_type_);
}

// ===================================================================

class Metadata::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Metadata>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Metadata, _impl_._has_bits_);
};

Metadata::Metadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Metadata_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nearby.internal.Metadata)
}
PROTOBUF_NDEBUG_INLINE Metadata::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nearby::internal::Metadata& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        account_name_(arena, from.account_name_),
        device_name_(arena, from.device_name_),
        user_name_(arena, from.user_name_),
        device_profile_url_(arena, from.device_profile_url_),
        bluetooth_mac_address_(arena, from.bluetooth_mac_address_) {}

Metadata::Metadata(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Metadata& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Metadata_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Metadata* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, device_type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, device_type_),
           offsetof(Impl_, instance_type_) -
               offsetof(Impl_, device_type_) +
               sizeof(Impl_::instance_type_));

  // @@protoc_insertion_point(copy_constructor:nearby.internal.Metadata)
}
PROTOBUF_NDEBUG_INLINE Metadata::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        account_name_(arena),
        device_name_(arena),
        user_name_(arena),
        device_profile_url_(arena),
        bluetooth_mac_address_(arena) {}

inline void Metadata::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, device_type_),
           0,
           offsetof(Impl_, instance_type_) -
               offsetof(Impl_, device_type_) +
               sizeof(Impl_::instance_type_));
}
Metadata::~Metadata() {
  // @@protoc_insertion_point(destructor:nearby.internal.Metadata)
  SharedDtor(*this);
}
inline void Metadata::SharedDtor(MessageLite& self) {
  Metadata& this_ = static_cast<Metadata&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.account_name_.Destroy();
  this_._impl_.device_name_.Destroy();
  this_._impl_.user_name_.Destroy();
  this_._impl_.device_profile_url_.Destroy();
  this_._impl_.bluetooth_mac_address_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Metadata::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Metadata(arena);
}
constexpr auto Metadata::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Metadata),
                                            alignof(Metadata));
}
constexpr auto Metadata::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<25>{
      {
          &_Metadata_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Metadata::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<Metadata>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Metadata::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<Metadata>(), &Metadata::ByteSizeLong,
              &Metadata::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Metadata, _impl_._cached_size_),
          true,
      },
      "nearby.internal.Metadata",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<25> Metadata_class_data_ =
    Metadata::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Metadata::GetClassData() const {
  return Metadata_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 83, 2>
Metadata::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Metadata, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Metadata_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nearby::internal::Metadata>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .nearby.internal.DeviceType device_type = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 5, 0,
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.device_type_)}},
    // string account_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.account_name_)}},
    // string device_name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.device_name_)}},
    // string user_name = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.user_name_)}},
    // string device_profile_url = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 3, 0,
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.device_profile_url_)}},
    // bytes bluetooth_mac_address = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 4, 0,
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.bluetooth_mac_address_)}},
    // .nearby.internal.InstanceType instance_type = 7;
    {::_pbi::TcParser::FastV32S1,
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.instance_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .nearby.internal.DeviceType device_type = 1;
    {PROTOBUF_FIELD_OFFSET(Metadata, _impl_.device_type_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string account_name = 2;
    {PROTOBUF_FIELD_OFFSET(Metadata, _impl_.account_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string device_name = 3;
    {PROTOBUF_FIELD_OFFSET(Metadata, _impl_.device_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string user_name = 4;
    {PROTOBUF_FIELD_OFFSET(Metadata, _impl_.user_name_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string device_profile_url = 5;
    {PROTOBUF_FIELD_OFFSET(Metadata, _impl_.device_profile_url_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes bluetooth_mac_address = 6;
    {PROTOBUF_FIELD_OFFSET(Metadata, _impl_.bluetooth_mac_address_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // .nearby.internal.InstanceType instance_type = 7;
    {PROTOBUF_FIELD_OFFSET(Metadata, _impl_.instance_type_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\30\0\14\13\11\22\0\0"
    "nearby.internal.Metadata"
    "account_name"
    "device_name"
    "user_name"
    "device_profile_url"
  }},
};
PROTOBUF_NOINLINE void Metadata::Clear() {
// @@protoc_insertion_point(message_clear_start:nearby.internal.Metadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.account_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.device_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.user_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.device_profile_url_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.bluetooth_mac_address_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000060U)) {
    ::memset(&_impl_.device_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.instance_type_) -
        reinterpret_cast<char*>(&_impl_.device_type_)) + sizeof(_impl_.instance_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Metadata::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Metadata& this_ = static_cast<const Metadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Metadata::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Metadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nearby.internal.Metadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .nearby.internal.DeviceType device_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_device_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_device_type(), target);
    }
  }

  // string account_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_account_name().empty()) {
      const ::std::string& _s = this_._internal_account_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.Metadata.account_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string device_name = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_device_name().empty()) {
      const ::std::string& _s = this_._internal_device_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.Metadata.device_name");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string user_name = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_user_name().empty()) {
      const ::std::string& _s = this_._internal_user_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.Metadata.user_name");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // string device_profile_url = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_device_profile_url().empty()) {
      const ::std::string& _s = this_._internal_device_profile_url();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nearby.internal.Metadata.device_profile_url");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // bytes bluetooth_mac_address = 6;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_bluetooth_mac_address().empty()) {
      const ::std::string& _s = this_._internal_bluetooth_mac_address();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // .nearby.internal.InstanceType instance_type = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_instance_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          7, this_._internal_instance_type(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nearby.internal.Metadata)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Metadata::ByteSizeLong(const MessageLite& base) {
  const Metadata& this_ = static_cast<const Metadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Metadata::ByteSizeLong() const {
  const Metadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nearby.internal.Metadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // string account_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_account_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_account_name());
      }
    }
    // string device_name = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_device_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_device_name());
      }
    }
    // string user_name = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_user_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_user_name());
      }
    }
    // string device_profile_url = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_device_profile_url().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_device_profile_url());
      }
    }
    // bytes bluetooth_mac_address = 6;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_bluetooth_mac_address().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_bluetooth_mac_address());
      }
    }
    // .nearby.internal.DeviceType device_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_device_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_device_type());
      }
    }
    // .nearby.internal.InstanceType instance_type = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_instance_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_instance_type());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void Metadata::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Metadata*>(&to_msg);
  auto& from = static_cast<const Metadata&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nearby.internal.Metadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_account_name().empty()) {
        _this->_internal_set_account_name(from._internal_account_name());
      } else {
        if (_this->_impl_.account_name_.IsDefault()) {
          _this->_internal_set_account_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_device_name().empty()) {
        _this->_internal_set_device_name(from._internal_device_name());
      } else {
        if (_this->_impl_.device_name_.IsDefault()) {
          _this->_internal_set_device_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_user_name().empty()) {
        _this->_internal_set_user_name(from._internal_user_name());
      } else {
        if (_this->_impl_.user_name_.IsDefault()) {
          _this->_internal_set_user_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_device_profile_url().empty()) {
        _this->_internal_set_device_profile_url(from._internal_device_profile_url());
      } else {
        if (_this->_impl_.device_profile_url_.IsDefault()) {
          _this->_internal_set_device_profile_url("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_bluetooth_mac_address().empty()) {
        _this->_internal_set_bluetooth_mac_address(from._internal_bluetooth_mac_address());
      } else {
        if (_this->_impl_.bluetooth_mac_address_.IsDefault()) {
          _this->_internal_set_bluetooth_mac_address("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_device_type() != 0) {
        _this->_impl_.device_type_ = from._impl_.device_type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_instance_type() != 0) {
        _this->_impl_.instance_type_ = from._impl_.instance_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void Metadata::CopyFrom(const Metadata& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nearby.internal.Metadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Metadata::InternalSwap(Metadata* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_name_, &other->_impl_.account_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_name_, &other->_impl_.device_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_name_, &other->_impl_.user_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_profile_url_, &other->_impl_.device_profile_url_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bluetooth_mac_address_, &other->_impl_.bluetooth_mac_address_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Metadata, _impl_.instance_type_)
      + sizeof(Metadata::_impl_.instance_type_)
      - PROTOBUF_FIELD_OFFSET(Metadata, _impl_.device_type_)>(
          reinterpret_cast<char*>(&_impl_.device_type_),
          reinterpret_cast<char*>(&other->_impl_.device_type_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace internal
}  // namespace nearby
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
