cc_binary(
    name = "connectionsd",
    srcs = ["main.cc"],
    deps = ["//connections:core",
            "//connections:core_types",
            "//internal/platform/implementation/linux:linux"],
)
