cc_library(
    name = "device",
    hdrs = [
        "device.h",
    ],
    visibility = [
        "//connections:__subpackages__",
        "//presence:__subpackages__",
    ],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
    ],
)
