cc_library(
    name = "sample_wifi_medium",
    srcs = [
        "sample_wifi_medium.cc",
    ],
    hdrs = [
        "sample_wifi_medium.h",
    ],
    visibility = [
        "//googlemac/iPhone/Shared/Nearby/Connections:__subpackages__",
        "//core:__subpackages__",
        "//platform/impl:__subpackages__",
    ],
    deps = [
        "//platform:types",
        "//platform:utils",
        "//platform/api",
        "//platform/port:string",
        "//absl/time",
    ],
)
